### ISSUE TITLE
Code lookup actually toggling

### ISSUE THREAD

**Issue by dimateos** [pthom/imgui_manual#10]
Hello again!

Code lookup is fantastic, but right now the shortcut `Ctrl+Alt+C` is not actually _toggling_ it as the tooltip suggests, instead it just turns it on (then ESC to turn off).

Found the line, so [`GImGuiDemoMarker_IsActive = !GImGuiDemoMarker_IsActive;`](https://github.com/pthom/imgui/blob/6248b45666d051b21758432976c7fb49d4d6958a/imgui_demo.cpp#L8355) would be my choice ;)

Thanks again!!

**Comment by pthom** [comment]
Thanks, this is fixed in https://github.com/pthom/imgui_manual/commit/11180865461f658548f7805c3ef2941361b3ec3a
