### ISSUE TITLE
Build error - cmake file command

### ISSUE THREAD

**Issue by h1z1** [pthom/imgui_manual#2]
Curious what version this was introduced in cmake?

https://github.com/pthom/imgui_manual/blob/88e3434beece04de5479b4c13b4191d3788d8660/src/make_example_apps/CMakeLists.txt#L4

Results in a build error

```
CMake` Error at src/make_example_apps/CMakeLists.txt:4 (file):
  file does not recognize sub-command CREATE_LINK

```

That appears to be something completely different according to cmake v3  (doesn't exist at all for file)

**Comment by pthom** [comment]
Hi, thanks for letting me know. This was introduced in cmake 3.14. I just added [this commit] which requires version 3.14, as well as some corrections for windows compil.
