### ISSUE TITLE
Is ImPlot online demo related ? Can't copy selected code from ImPlot online manual.

### ISSUE THREAD

**Issue by Maksons** [pthom/imgui_manual#5]
Hello, 

I do use online manuals of ImGui and ImPlot, but in ImPlot online manual it's not possible to copy selected code.
I check ImGui manual and there is possible to copy, so problem related to ImPlot manual.

Is it right place to report the issue ?

**Comment by pthom** [comment]
Hello,


Thanks for the report. Copy / Paste with WebAsm is not that easy. See for example an explanation at https://github.com/pthom/hello_imgui/issues/3

Anyhow, I backported the trick I used for imgui manual into implot demo. It should work now.
