### ISSUE TITLE
Acknowledgement github url open multiple times

### ISSUE THREAD

**Issue by jrynkiew** [pthom/imgui_manual#6]
In Acknowledgements you use the strings defined in Sources.cpp, like so:

`"imgui_markdown", "imgui_markdown", "https://github.com/juliettef/imgui_markdown"`

The first parameter is a LibraryFolderPath and the next two are strings.

Then in LibrariesCodeBrowser.cpp you use this data to display the strings and the markdowns, but on line 55 you use the url as a `ImGuiExt::Hyperlink(librarySource.url); `

This is causing problems on Firefox 89.02 x64 where clicking the link opens multiple tabs and effectively the whole imgui application needs to be reloaded, as even hovering over the markdown window will keep on opening new tabs :package: 

I recommend changing to `MarkdownHelper::Markdown(librarySource.url);` as it's just a string anyway, and it gives you the additional benefit of having a hover over effect also for this link. [ edit: Of course you will need to edit the acknowledgement URL's and format them in the markdown style of `[text] (url)` :) ]

**Comment by pthom** [comment]
Hello,

Nice catch, thanks for the detailed explanation. I just fixed this :-)
